<?php
/**
 * @file
 * Code for the Intrigues feature.
 */

include_once 'intrigues.features.inc';

// -----------------------------------------------------------------------------
// ACCESS CONTROL

/**
 * Implements hook_permission().
 */
function intrigues_permission() {
  return array(
    'view all intrigues' => array(
      'title' => t('View all intrigues without being restricted.'),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function intrigues_node_access($node, $op, $account) {
  $return = NODE_ACCESS_IGNORE;

  if ($op == 'view' && $node->type == 'intrigue') {
    $return = NODE_ACCESS_DENY;
    if (user_access('view all intrigues')) {
      $return = NODE_ACCESS_ALLOW;
    }
  }

  return $return;
}

// -----------------------------------------------------------------------------
// EXTRA FIELDS

/**
 * Implements hook_field_extra_fields().
 */
function intrigues_field_extra_fields() {
  $extras = array();

  $extras['node']['intrigue']['display']['view_events'] = array(
    'label' => t('Views events'),
    'weight' => 99,
  );
  $extras['node']['intrigue']['display']['view_infos'] = array(
    'label' => t('Views infos'),
    'weight' => 99,
  );
  $extras['node']['intrigue']['display']['view_sequences'] = array(
    'label' => t('Views sequences'),
    'weight' => 99,
  );

  return $extras;
}

/**
 * Implements hook_node_view().
 */
function intrigues_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'intrigue') {
    $view_content = views_embed_view('admin_evenements', 'block_by_intrigue', $node->nid);
    $node->content['view_events'] = _config_base_extra_field_view('view_events', 'Evènements liés à l\'intrigue', $node, $view_mode, $langcode, $view_content, user_access('view all intrigues'));

    $view_content = views_embed_view('admin_informations', 'block_by_intrigue', $node->nid);
    $node->content['view_infos'] = _config_base_extra_field_view('view_infos', 'Informations liées à l\'intrigue', $node, $view_mode, $langcode, $view_content, user_access('view all intrigues'));

    $view_content = views_embed_view('admin_sequences', 'block_by_intrigue', $node->nid);
    $node->content['view_sequences'] = _config_base_extra_field_view('view_sequences', 'Séquences liées à l\'intrigue', $node, $view_mode, $langcode, $view_content, user_access('view all intrigues'));
  }
}
