<?php
/**
 * @file
 * Code for the Administration feature.
 */

include_once 'administration.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 */
function administration_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $link = FALSE;
  switch ($root_path) {
    case 'admin/cec/avantages':
      $link = menu_get_item('node/add/avantage');
      break;
    case 'admin/cec/evenements':
      $link = menu_get_item('node/add/event');
      break;
    case 'admin/cec/groupes':
      $link = menu_get_item('node/add/group');
      break;
    case 'admin/cec/informations':
      $link = menu_get_item('node/add/information');
      break;
    case 'admin/cec/intrigues':
      $link = menu_get_item('node/add/intrigue');
      break;
    case 'admin/cec/personnages':
      $link = menu_get_item('node/add/character');
      break;
    case 'admin/cec/lieux':
      $link = menu_get_item('node/add/location');
      break;
    case 'admin/cec/materiel':
      $link = menu_get_item('node/add/stuff');
      break;
    case 'admin/cec/sequences':
      $link = menu_get_item('node/add/sequence');
      break;
    case 'search':
      $data['tabs'][0]['count'] = 0;
      $data['tabs'][0]['output'] = array();
      break;
  }
  if (!empty($link)) {
    $link['title'] = 'Créer ' . $link['title'];
    $data['actions']['output'][] = array(
      '#theme' => 'menu_local_action',
      '#link' => $link,
    );
  }
}

// -----------------------------------------------------------------------------
// EXTRA FIELDS

/**
 * Implements hook_field_extra_fields().
 */
function administration_field_extra_fields() {
  $extras = array();

  $types = node_type_get_types();
  unset($types['news']);
  unset($types['page']);
  foreach ($types  as $machine_name => $type) {
    $extras['node'][$machine_name]['display']['comments'] = array(
      'label' => t('Comments'),
      'weight' => 99,
    );
    $extras['node'][$machine_name]['display']['cec_comments'] = array(
      'label' => t('CEC Comments'),
      'weight' => 99,
    );
  }

  return $extras;
}

/**
 * Implements hook_node_view().
 */
function administration_node_view($node, $view_mode, $langcode) { 
  if (!empty($node->comment)) {
    $node->content['cec_comments'] = 
    $node->content['comments'] = comment_node_page_additions($node);
  }
}
