<?php
/**
 * @file
 * Code for the Séquences feature.
 */

include_once 'sequences.features.inc';

/**
 * Implements hook_form_alter().
 */
function sequences_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'sequence_node_form') {
    if (empty($form['field_dates'][LANGUAGE_NONE][0]['#default_value']['value'])) {
      $form['field_dates'][LANGUAGE_NONE][0]['#default_value'] = array(
        'value' => '2017-04-27 16:00:00',
        'value2' => '2017-05-01 16:00:00',
        'timezone' => 'Europe/Paris',
        'timezone_db' => 'Europe/Paris',
        'date_type' => 'datetime',
      );
    }
    $form['#attached']['js'][] = drupal_get_path('module', 'sequences') . '/sequences.js';
  }
}

/**
 * Implements hook_date_select_process_alter().
 */
function sequences_date_select_process_alter(&$element, &$form_state, $context) {
  if ($context['form']['#form_id'] == 'sequence_node_form') {
    $element['day']['#options'] = array(27 => 'Jeudi 27', 28 => 'Vendredi 28', 29 => 'Samedi 29', 30 => 'Dimanche 30', 01 => 'Lundi 1er');
    $element['month']['#options'] = array(04 => 'Avril', 05 => 'Mai');
  }
}
