<?php
/**
 * @file
 * Code for the Config Base feature.
 */

include_once 'config_base.features.inc';

/**
 * Prepare field renderable array for views extra fields.
 */
function _config_base_extra_field_view($field_name, $title, $node, $view_mode, $langcode, $view_content, $access = TRUE) {
  return array(
    '#theme' => 'field',
    '#label_display' => empty($title) ? 'hidden' : 'above',
    '#node' => $node,
    '#view_mode' => $view_mode,
    '#language' => $langcode,

    '#entity_type' => 'node',
    '#bundle' => $node->type,

    '#field_name' => 'extra_field_' . $field_name,
    '#field_type' => 'extra_field_view',
    '#field_translatable' => FALSE,
    '#object' => $node,
    '#formatter' => NULL,

    '#title' => $title,
    '#access' => $access,
    '#items' => array(
      0 => array(
        'value' => $view_content,
        'format' => NULL,
        'safe_value' => $view_content,
      ),
    ),
    0 => array(
      '#markup' => $view_content,
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function config_base_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'config_base') . '/includes',
  );
}

/**
 * Implements hook_views_data_alter().
 */
function config_base_views_data_alter(&$data) {
  $data['workflow_node']['sid']['field']['handler'] = 'workflow_views_handler_field_sid_transliterated';
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function config_base_wysiwyg_editor_settings_alter(&$settings, $context) {
  if($context['profile']->editor == 'ckeditor') {
    $settings['disableNativeSpellChecker'] = FALSE;
    $settings['scayt_autoStartup'] = TRUE;
    $settings['scayt_sLang'] = 'fr_FR';
    $settings['scayt_userDictionaryName'] = 'GN_CeC';
  }
}

/*
 * Implements hook_date_format_types().
 */
function config_base_date_format_types() {
  variable_set('date_format_date_only', 'd/m/Y');
  variable_set('date_format_date_only_evt', 'd F Y');
  return array(
    'date_only' => t('Date only'),
    'date_only_evt' => t('Date only event'),
  );
}

/*
 * Implements hook_date_formats().
 */
function config_base_date_formats() {
  $formats = array();

  // Short date formats.
  $formats[] = array(
    'type' => 'date_only',
    'format' => 'd/m/Y',
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'date_only_evt',
    'format' => 'd F Y',
    'locales' => array(),
  );

  return $formats;
}
