<?php
/**
 * @file
 * Improve profiles forms.
 */

define('CEC_PROFILES_LIMIT', '15 août 2012');

/**
 * Implements hook_permission().
 */
function cec_profiles_permission() {
  return array(
    'access profile opus' => array(
      'title' => t('Access Opus field on profiles'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function cec_profiles_form_alter(&$form, &$form_state, $form_id) {
  // profil_joueur profile form
  if ($form_id == 'profile2_edit_profil_joueur_form') {
    $voc = taxonomy_vocabulary_machine_name_load('temperament');
    $terms = taxonomy_get_tree($voc->vid);
    $exclusion = array();
    foreach ($terms as $term) {
      $term = taxonomy_term_load($term->tid);
      $antonym = field_get_items('taxonomy_term', $term, 'field_antonym');
      $exclusion[$term->tid] = $antonym[0]['tid'];
    }
    drupal_add_js(array('temperaments_exclusion' => $exclusion), 'setting');
    drupal_add_js(drupal_get_path('module', 'cec_profiles') . '/cec_profiles.js');
  }
  
  // All profile forms
  if (strpos($form_id, 'profile2_') === 0) {
    $profile_type = substr($form_id, 14, -5);
    if (!empty($form['profile_' . $profile_type]['field_opus'])) {
      $form['profile_' . $profile_type]['field_opus']['#access'] = user_access('access profile opus');
    }
  }
}

/**
 * Implements hook_mail().
 */
function cec_profiles_mail($key, &$message, $params) {
  $urlHome = url('<front>', array('absolute' => TRUE));
  $urlAdmin = url('profile-inscription_administrative', array('absolute' => TRUE));
  $urlProfil = url('profile-profil_joueur', array('absolute' => TRUE));
  $urlPaiement = url('reglement', array('absolute' => TRUE));
  $urlEntracte = url('http://docs.google.com/spreadsheet/viewform?formkey=dHE1STJzS3ltSjAxTm82VmI3Z25RVEE6MQ', array('external' => TRUE));

  $msg = '';
  if ($key == 'new_subscription') {
    $msg .= 'Bonjour ' . $params['firstname'] . ',<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Votre pré-inscription au GN Capes & Crocs Acte II a été retenue.<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Vous pouvez désormais accéder à un espace personnel sur <a href="' . $urlHome . '">le site</a> en utilisant les identifiant suivants :<br />' . "\n";
    $msg .= 'Identifiant : ' . $params['login'] . '<br />' . "\n";
    $msg .= 'Mot de passe : ' . $params['pass'] . '<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Afin que votre inscription soit validée, nous avons besoin de recevoir <strong>avant le ' . CEC_PROFILES_LIMIT . '</strong> les éléments suivants :<br />' . "\n";
    $msg .= '<ol>' . "\n";
    $msg .= '  <li>le formulaire d\'inscription administrative complété (<a href="' . $urlAdmin . '">y accéder</a>)</li>' . "\n";
    $msg .= '  <li>le règlement pour l\'inscription au GN (<a href="' . $urlPaiement . '">consulter les détails</a>)</li>' . "\n";
    if ($params['is_new_player']) {
      $msg .= '  <li>le formulaire de personnage complété (<a href="' . $urlProfil . '">y accéder</a>)</li>' . "\n";
    } 
    elseif ($params['is_new_character']) {
      $msg .= '  <li>le formulaire de personnage complété, <strong>le choix ayant été fait de ne pas conserver celui de l\'Acte précédent</strong> (<a href="' . $urlProfil . '">y accéder</a>)</li>' . "\n";
    }
    else {
      $msg .= '  <li>le formulaire d\'Entr\'Acte nous permettant de déterminer les actions de votre personnage durant les quelques mois qui séparent cet Acte du précédent (<a href="' . $urlEntracte . '">y accéder</a>)</li>' . "\n";
      $msg .= '  <li>le formulaire de personnage complété avec les même informations que lors de votre inscription à l\'Acte précédent. Si vous ne vous en souvenez pas, laissez le vide nous le complèterons nous-même (<a href="' . $urlProfil . '">y accéder</a>)</li>' . "\n";
    }
    $msg .= '</ol><br />' . "\n";
    $msg .= '<i>Note : comme nous avons beaucoup de joueurs sur liste d\'attente, passé le ' . CEC_PROFILES_LIMIT . ', si nous n\'avons pas de nouvelles de votre part, nous proposerons votre place à un autre joueur.</i><br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Ludiquement votre,<br />' . "\n";
    $msg .= 'Les Zorgas Capes & Crocs';
  }
  elseif ($key == 'new_subscription_awaiting') {
    $msg .= 'Bonjour ' . $params['firstname'] . ',<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Nous avons bien reçu votre pré-inscription au GN Capes & Crocs Acte II.<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Elle est pour le moment placée sur la <strong>liste d\'attente</strong>.<br />' . "\n";
    $msg .= 'Cela signifie que le GN est complet mais si nous avons des désistements, nous pourrons vous proposer une place.<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Pour cela, nous avons besoin que vous complétiez rapidement <a href="' . $urlProfil . '">le formulaire de personnage en ligne</a>.<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Pour ce faire, vous pouvez désormais accéder à un espace personnel sur <a href="' . $urlHome . '">le site</a> en utilisant les identifiant suivants :<br />' . "\n";
    $msg .= 'Identifiant : ' . $params['login'] . '<br />' . "\n";
    $msg .= 'Mot de passe : ' . $params['pass'] . '<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Nous vous recontacterons après le ' . CEC_PROFILES_LIMIT . ' pour vous tenir informé.<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= '<br />' . "\n";
    $msg .= 'Ludiquement votre,<br />' . "\n";
    $msg .= 'Les Zorgas Capes & Crocs';
  }

  $message['subject'] = '[GN C&C] Votre pré-inscription au GN Capes & Crocs Acte II';
  $message['body'] = array($msg);
}

/**
 * Import users from CSV extracted from GDocs
 * 
 * $line[0] : VIDE
 * $line[1] : Date
 * $line[2] : Nom
 * $line[3] : VIDE
 * $line[4] : Prénom
 * $line[5] : Mail
 * $line[6] : Téléphone
 * $line[7] : Ancien joueur ? OUI/NON
 * $line[8] : Inscription validée ? OUI/Liste attente
 * $line[9] : Nom perso
 * $line[10] : Souhait conserver ? OUI/NON/NOUVEAU
 * $line[11] : Demande Zorga ? X/VIDE
 * $line[12] : Souhait groupe ? OUI/NON
 * $line[13] : Groupe
 * 
 * @params $file
 *   The CSV file
 */
function cec_profiles_import_from_csv($file) {
  // Check file existance
  if (!is_file($file)) {
    throw new Exception('The file ' . $file . ' does not exists');
  }

  // Open file
  $f = fopen($file, 'r+');
  if ($f === FALSE) {
    throw new Exception('The file ' . $file . ' is not readable');
  }
  
  // Process file
  $user_roles = user_roles(TRUE);
  while (($line = fgetcsv($f)) !== FALSE) {
    if ($line[2] == 'Nom' && $line[5] == 'Adresse email') { continue; } // Jump headers
    $line = array_map('trim', $line); // Remove trailing spaces
    
    $login = transliteration_clean_filename($line[4] . ' ' . $line[2]);
    $pass = user_password();
    $mail = $line[5];
    $roles = array();
    $rid = array_search('Joueur', $user_roles);
    $roles[$rid] = TRUE;
    if ($line[8] == 'Liste attente') {
      $rid = array_search('Inscription en liste d\'attente', $user_roles);
      $roles[$rid] = TRUE;
    } elseif ($line[8] == 'OUI') {
      $rid = array_search('Inscription validée', $user_roles);
      $roles[$rid] = TRUE;
    }

    $account = user_load_by_mail($mail);
    if ($account === FALSE) {
      // Account creation
      $new_user = array(
        'name' => $login,
        'pass' => $pass,
        'mail' => $mail,
        'status' => 1,
        'roles' => $roles,
        'data' => array(
          'firstname' => $line[4],
          'lastname' => $line[2],
          'charname' => $line[9],
        ),
      );
      $account = user_save(null, $new_user);
      
      // Send mail to new user
      $params = array(
        'firstname' => $line[4],
        'lastname' => $line[2],
        'login' => $login,
        'pass' => $pass,
        'email' => $mail,
        'is_accepted' => $line[8] == 'OUI', // Inscrit / Liste attente
        'is_new_player' => $line[7] == 'NON', // Nouveau / Ancien joueur
        'is_new_character' => $line[10] != 'OUI' || $line[11] == 'X', // Change / Garde perso
      );
      $key = $params['is_accepted'] ? 'new_subscription' : 'new_subscription_awaiting';
      drupal_mail('cec_profiles', $key, $mail, language_default(), $params);
    }
    else {
      watchdog('cec_profiles', 'Account @mail already exists.', array('@mail' => $mail));
    }
  }
  
  fclose($f);
    
}