<?php
/**
 * @file
 * Improve profiles forms.
 */

define('CEC_PROFILES_LIMIT', '20 juillet 2012');

/**
 * Implements hook_permission().
 */
function cec_profiles_permission() {
  return array(
    'access profile opus' => array(
      'title' => t('Access Opus field on profiles'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cec_profiles_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#user_category'] == 'profil_joueur') {
    $voc = taxonomy_vocabulary_machine_name_load('temperament');
    $terms = taxonomy_get_tree($voc->vid);
    $exclusion = array();
    foreach ($terms as $term) {
      $term = taxonomy_term_load($term->tid);
      $antonym = field_get_items('taxonomy_term', $term, 'field_antonym');
      $exclusion[$term->tid] = $antonym[0]['tid'];
    }
    drupal_add_js(array('temperaments_exclusion' => $exclusion), 'setting');
    drupal_add_js(drupal_get_path('module', 'cec_profiles') . '/cec_profiles.js');
  }
  if (!empty($form['profile_' . $form['#user_category']]['field_opus'])) {
    $form['profile_' . $form['#user_category']]['field_opus']['#access'] = user_access('access profile opus');
  }
}

/**
 * Implements hook_mail().
 */
function cec_profiles_mail($key, &$message, $params) {
  $urlHome = url('<front>', array('absolute' => TRUE));
  $urlAdmin = url('user/me/edit/inscription_administrative', array('absolute' => TRUE));
  $urlProfil = url('user/me/edit/profil_joueur', array('absolute' => TRUE));
  $urlPaiement = url('reglement', array('absolute' => TRUE));
  
  $msg = '';
  if ($key == 'new_subscription') {
    $msg .= 'Bonjour ' . $params['firstname'] . ',<br />';
    $msg .= '<br />';
    $msg .= '<br />';
    $msg .= 'Votre pré-inscription au GN Capes & Crocs Acte II du 09 au 12 mais 2013 a été retenue.<br />';
    $msg .= '<br />';
    $msg .= 'Vous pouvez désormais accéder à un espace personnel sur <a href="' . $urlHome . '">le site</a> en utilisant les identifiant suivants :<br />';
    $msg .= 'Identifiant : ' . $params['login'] . '<br />';
    $msg .= 'Mot de passe : ' . $params['pass'] . '<br />';
    $msg .= '<br />';
    $msg .= 'Afin que votre inscription soit validée, nous avons besoin de recevoir <strong>avant le ' . CEC_PROFILES_LIMIT . '</strong> les éléments suivants :<br />';
    $msg .= '<ol>';
    $msg .= '<li>le formulaire d\'inscription administrative complété (<a href="' . $urlAdmin . '">y accéder</a>)</li>';
    $msg .= '<li>le règlement pour l\inscription au GN (<a href="' . $urlPaiement . '">consulter les détails</a>)</li>';
    if ($params['is_new_player']) {
      $msg .= '<li>le formulaire de personnage complété (<a href="' . $urlProfil . '">y accéder</a>)</li>';
    } 
    elseif ($params['is_new_character']) {
      $msg .= '<li>le formulaire de personnage complété, <strong>le choix ayant été fait de ne pas conserver celui de l\'Acte précédent</strong>. (<a href="' . $urlProfil . '">y accéder</a>)</li>';
    }
    else {
      $msg .= '<li>le formulaire de personnage complété avec les même informations que lors de votre inscription à l\'Acte précédent. Si vous ne vous en souvenez pas, laissez le vide nous le complèterons nous-même. (<a href="' . $urlProfil . '">y accéder</a>)</li>';
    }
    $msg .= '</ol><br />';
    $msg .= '<i>Note : comme nous avons beaucoup de joueurs sur liste d\'attente, passé le ' . CEC_PROFILES_LIMIT . ', si nous n\'avons pas de nouvelles de votre part, nous proposerons votre place à un autre joueur.</i><br />';
    $msg .= '<br />';
    $msg .= '<br />';
    $msg .= 'Ludiquement votre,<br />';
    $msg .= 'Les Zorgas Capes & Crocs';
  }
  elseif ($key == 'new_subscription_awaiting') {
    $msg .= 'Bonjour ' . $params['firstname'] . ',<br />';
    $msg .= '<br />';
    $msg .= '<br />';
    $msg .= 'Nous avons bien reçu votre pré-inscription au GN Capes & Crocs Acte II du 09 au 12 mais 2013.<br />';
    $msg .= '<br />';
    $msg .= 'Elle est pour le moment placée sur la <strong>liste d\'attente</strong>.<br />';
    $msg .= 'Qu\'est-ce que cela veut dire ? Et bien voilà, le GN est complet mais si nous avons des désistements, nous pourrons vous proposer une place.<br />';
    $msg .= '<br />';
    $msg .= 'Pour cela, nous avons besoin que vous complétiez rapidement <a href="' . $urlProfil . '">le formulaire de personnage en ligne</a>.<br />';
    $msg .= '<br />';
    $msg .= 'Pour ce faire, vous pouvez désormais accéder à un espace personnel sur <a href="' . $urlHome . '">le site</a> en utilisant les identifiant suivants :<br />';
    $msg .= 'Identifiant : ' . $params['login'] . '<br />';
    $msg .= 'Mot de passe : ' . $params['pass'] . '<br />';
    $msg .= '<br />';
    $msg .= 'Nous vous recontacterons dans le courant du mois d\'août pour vous tenir informé.<br />';
    $msg .= '<br />';
    $msg .= '<br />';
    $msg .= 'Ludiquement votre,<br />';
    $msg .= 'Les Zorgas Capes & Crocs';
  }

  $message['subject'] = '[GN C&C] Votre pré-inscription au GN Capes & Crocs Acte II';
  $message['body'] = array($msg);
}
