<?php
/**
 * @file
 * Code for the Groupes feature.
 */

include_once 'groupes.features.inc';

/**
 * Implements hook_permission().
 */
function groupes_permission() {
  return array(
    'view all groups' => array(
      'title' => t('View all groups without being restricted.'),
    ),
    'view technical groups' => array(
      'title' => t('View technical groups without being restricted.'),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function groupes_node_access($node, $op, $account) {
  global $user;
  $return = NODE_ACCESS_IGNORE;

  if ($op == 'view' && $node->type == 'group') {
    $return = NODE_ACCESS_DENY;
    if (user_access('view all groups')) {
      $return = NODE_ACCESS_ALLOW;
    }
    else {
      $technical = reset(field_get_items('node', $node, 'field_group_is_technical'));
      $technical = $technical['value'] == 1;
      if ($technical && user_access('view technical groups')) {
        $return = NODE_ACCESS_ALLOW;
      }
      elseif (!$technical) {
        $members = field_get_items('node', $node, 'field_group_members');
        foreach ($members as $member) {
          $collection = field_collection_item_load($member['value']);
          $character = reset(field_get_items('field_collection_item', $collection, 'field_character'));
          $character = node_load($character['target_id']);
          $return = personnages_node_access($character, $op, $account);
        }
      }
    }
  }

  return $return;
}

// -----------------------------------------------------------------------------
// EXTRA FIELDS

/**
 * Implements hook_field_extra_fields().
 */
function groupes_field_extra_fields() {
  $extras = array();

  $extras['node']['group']['display']['view_events'] = array(
    'label' => t('Views events'),
    'weight' => 99,
  );
  $extras['node']['group']['display']['view_infos'] = array(
    'label' => t('Views infos'),
    'weight' => 99,
  );
  $extras['node']['group']['display']['zorgas_links'] = array(
    'label' => t('Zorga Links'),
    'weight' => 99,
  );

  return $extras;
}

/**
 * Implements hook_node_view().
 */
function groupes_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'group') {
    global $user;
    $rid = array_search('Zorga', $user->roles);
    $is_zorga = !empty($rid);

    $view_content = views_embed_view('admin_evenements', 'block_by_group', $node->nid);
    $node->content['view_events'] = _config_base_extra_field_view('view_events', 'Evènements liés au groupe', $node, $view_mode, $langcode, $view_content, $is_zorga);

    $view_content = views_embed_view('admin_informations', 'block_by_group', $node->nid);
    $node->content['view_infos'] = _config_base_extra_field_view('view_infos', 'Informations liées au groupe', $node, $view_mode, $langcode, $view_content, $is_zorga);

    $view_content = theme('item_list', array(
      'items' => array(
        l('Liste complète des événements du groupe', 'admin/cec/evenements/groupe/' . $node->nid),
        l('Liste complète des informations du groupe', 'admin/cec/informations/groupe/' . $node->nid),
      ),
    ));
    $node->content['zorgas_links'] = _config_base_extra_field_view('zorgas_links', 'Liens Zorgas', $node, $view_mode, $langcode, $view_content, $is_zorga);
  }
}
